name: Validate Kubernetes Manifests
description: Offline Kubernetes manifest validation using kubectl

inputs:
  stage:
    description: Environment stage label
    required: true

  deployment-dirs:
    description: Space-separated directories under kubernetes/
    required: true

runs:
  using: composite
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.28.0

    - name: Validate manifests
      shell: bash
      run: |
        set -euo pipefail

        export KUBECONFIG=/dev/null
        export KUBERNETES_MASTER=""

        read -r -a DIRS <<< "${{ inputs.deployment-dirs }}"

        for DIR in "${DIRS[@]}"; do
          MANIFEST_DIR="kubernetes/$DIR"

          if [ ! -d "$MANIFEST_DIR" ]; then
            echo "Directory not found: $MANIFEST_DIR" >&2
            exit 1
          fi

          shopt -s nullglob
          FILES=("$MANIFEST_DIR"/*.yml "$MANIFEST_DIR"/*.yaml)
          shopt -u nullglob

          if [ "${#FILES[@]}" -eq 0 ]; then
            echo "No manifests found in $MANIFEST_DIR" >&2
            exit 1
          fi

          kubectl apply \
            --dry-run=client \
            --validate=false \
            -f "$MANIFEST_DIR"
        done

        echo "✔ ${{ inputs.stage }} manifest validation passed" >> "$GITHUB_STEP_SUMMARY"
