name: Validate Kubernetes Manifests
description: Offline Kubernetes manifest validation using kubectl.

inputs:
  stage:
    required: true

  kubectl-version:
    default: v1.28.0

  deployment-dirs:
    default: namespaces prometheus grafana loki mimir alloy opentelemetry ingress

runs:
  using: composite
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Validate manifests
      shell: bash
      run: |
        set -euo pipefail

        # Force kubectl offline
        export KUBECONFIG=/dev/null
        export KUBERNETES_MASTER=""

        DIRS="${{ inputs.deployment-dirs }}"
        read -r -a DIR_ARRAY <<< "$DIRS"

        for DIR in "${DIR_ARRAY[@]}"; do
          PATH_DIR="kubernetes/$DIR"

          if [[ ! -d "$PATH_DIR" ]]; then
            echo "Missing directory: $PATH_DIR" >&2
            exit 1
          fi

          shopt -s nullglob
          FILES=("$PATH_DIR"/*.yml "$PATH_DIR"/*.yaml)
          shopt -u nullglob

          if [[ ${#FILES[@]} -eq 0 ]]; then
            echo "No manifests in: $PATH_DIR" >&2
            exit 1
          fi

          kubectl apply \
            --dry-run=client \
            --validate=false \
            -f "$PATH_DIR"
        done

        echo "✔ ${{ inputs.stage }} validation passed (client dry-run)" >> "$GITHUB_STEP_SUMMARY"
