name: Validate Kubernetes Manifests
description: Offline Kubernetes manifest validation using Python YAML parsing.

inputs:
  stage:
    required: true

  deployment-dirs:
    default: namespaces prometheus grafana loki mimir alloy opentelemetry ingress

runs:
  using: composite
  steps:
    - name: Validate manifests
      shell: bash
      run: |
        set -euo pipefail

        DIRS="${{ inputs.deployment-dirs }}"
        read -r -a DIR_ARRAY <<< "$DIRS"

        for DIR in "${DIR_ARRAY[@]}"; do
          PATH_DIR="kubernetes/$DIR"

          if [[ ! -d "$PATH_DIR" ]]; then
            echo "Missing directory: $PATH_DIR" >&2
            exit 1
          fi

          shopt -s nullglob
          FILES=("$PATH_DIR"/*.yml "$PATH_DIR"/*.yaml)
          shopt -u nullglob

          if [[ ${#FILES[@]} -eq 0 ]]; then
            echo "No manifests in: $PATH_DIR" >&2
            exit 1
          fi

          for FILE in "${FILES[@]}"; do
            python3 - <<'PY' "$FILE"
import sys
import yaml
path = sys.argv[1]
try:
    with open(path, "r", encoding="utf-8") as f:
        for _ in yaml.safe_load_all(f):
            pass
except yaml.YAMLError as exc:
    raise SystemExit(f"{path}: {exc}")
except OSError as exc:
    raise SystemExit(f"{path}: {exc}")
PY
          done
        done

        echo "✔ ${{ inputs.stage }} validation passed (YAML parse)" >> "$GITHUB_STEP_SUMMARY"
