name: Validate Kubernetes Manifests
description: Offline YAML validation

inputs:
  stage:
    required: true
    description: Environment name

  deployment-dirs:
    required: true
    description: Space separated directories

runs:
  using: composite
  steps:
    - name: Validate YAML
      shell: bash
      run: |
        set -e

        pip3 install --quiet PyYAML

        for d in ${{ inputs.deployment-dirs }}; do
          for f in kubernetes/$d/*.y*ml; do
            python3 -c "import yaml,sys; list(yaml.safe_load_all(open(sys.argv[1])))" "$f"
          done
        done
