name: Validate Kubernetes Manifests
description: Offline YAML validation

inputs:
  stage:
    required: true
    description: Environment name

  deployment-dirs:
    required: true
    description: Space separated directories

runs:
  using: composite
  steps:
    - name: Validate YAML
      shell: bash
      run: |
        set -euo pipefail

        pip3 install --quiet PyYAML

        shopt -s nullglob
        for d in ${{ inputs.deployment-dirs }}; do
          files=(kubernetes/$d/*.y*ml)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No YAML files in kubernetes/$d" >&2
            exit 1
          fi
          for f in "${files[@]}"; do
            python3 -c "import yaml,sys; [doc for doc in yaml.safe_load_all(open(sys.argv[1], 'r'))]" "$f"
          done
        done
