name: Validate Kubernetes Manifests
description: Validate Kubernetes manifests using kubectl dry-run (client-side).

inputs:
  stage:
    description: Environment stage label for summary output.
    required: true

  kubectl-version:
    description: Kubectl version to install.
    default: v1.28.0

  deployment-dirs:
    description: Space-separated list of manifest directories under kubernetes/.
    required: false
    default: namespaces prometheus grafana loki mimir alloy opentelemetry ingress

  dry-run-mode:
    description: Kubectl dry-run mode (client or server).
    default: client

runs:
  using: composite
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Validate manifests
      shell: bash
      run: |
        set -euo pipefail

        DEFAULT_DIRS="namespaces prometheus grafana loki mimir alloy opentelemetry ingress"
        DIRS="${{ inputs.deployment-dirs }}"

        if [[ -z "${DIRS// }" ]]; then
          DIRS="$DEFAULT_DIRS"
        fi

        read -r -a DIR_ARRAY <<< "$DIRS"

        MODE="${{ inputs.dry-run-mode }}"
        VALIDATE_FLAG="--validate=false"

        PROCESSED_DIRS=0
        PROCESSED_FILES=0

        for DIR in "${DIR_ARRAY[@]}"; do
          PATH_DIR="kubernetes/${DIR}"

          if [[ ! -d "$PATH_DIR" ]]; then
            echo "Directory not found: $PATH_DIR" >&2
            exit 1
          fi

          shopt -s nullglob
          FILES=("$PATH_DIR"/*.yml "$PATH_DIR"/*.yaml)
          shopt -u nullglob

          if [[ ${#FILES[@]} -eq 0 ]]; then
            echo "No manifest files in: $PATH_DIR" >&2
            exit 1
          fi

          PROCESSED_DIRS=$((PROCESSED_DIRS + 1))
          PROCESSED_FILES=$((PROCESSED_FILES + ${#FILES[@]}))

          kubectl apply \
            --dry-run="$MODE" \
            $VALIDATE_FLAG \
            -f "$PATH_DIR"
        done

        echo "${{ inputs.stage }} validation completed." >> "$GITHUB_STEP_SUMMARY"
        echo "- Dry-run mode: $MODE" >> "$GITHUB_STEP_SUMMARY"
        echo "- Directories: $PROCESSED_DIRS" >> "$GITHUB_STEP_SUMMARY"
        echo "- Manifest files: $PROCESSED_FILES" >> "$GITHUB_STEP_SUMMARY"
