name: Validate Kubernetes Manifests
description: Offline YAML validation for Kubernetes manifests

inputs:
  stage:
    description: Environment stage
    required: true

  deployment-dirs:
    description: Space-separated directories under kubernetes/
    required: true

runs:
  using: composite
  steps:
    - name: Install PyYAML
      shell: bash
      run: |
        pip3 install --quiet PyYAML==6.0.2

    - name: Validate YAML files
      shell: bash
      run: |
        set -euo pipefail

        IFS=' ' read -r -a DIRS <<< "${{ inputs.deployment-dirs }}"

        for DIR in "${DIRS[@]}"; do
          BASE="kubernetes/$DIR"

          if [ ! -d "$BASE" ]; then
            echo "Missing directory: $BASE" >&2
            exit 1
          fi

          FOUND=false
          for FILE in "$BASE"/*.yml "$BASE"/*.yaml; do
            [ -e "$FILE" ] || continue
            FOUND=true
            python3 -c "import yaml,sys; yaml.safe_load_all(open(sys.argv[1]))" "$FILE"
          done

          if [ "$FOUND" = false ]; then
            echo "No YAML files in $BASE" >&2
            exit 1
          fi
        done

        echo "✔ ${{ inputs.stage }} YAML validation passed" >> "$GITHUB_STEP_SUMMARY"
