name: Validate Kubernetes Manifests
description: Apply manifest validation using kubectl dry-run for standard deployment directories.

inputs:
  stage:
    description: Environment stage label for summary output.
    required: true
  kubectl-version:
    description: Kubectl version to install.
    default: v1.28.0
  deployment-dirs:
    description: Space-separated list of manifest directories under kubernetes/.
    required: true
  dry-run-mode:
    description: Kubectl dry-run mode to use (client or server).
    default: client

runs:
  using: composite
  steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ inputs.kubectl-version }}

    - name: Validate manifests
      shell: bash
      run: |
        set -euo pipefail
        dirs="${{ inputs.deployment-dirs }}"
        if [[ "$dirs" =~ ^[[:space:]]*$ ]]; then
          echo "No deployment directories provided; cannot validate." >&2
          exit 1
        fi

        mode="${{ inputs.dry-run-mode }}"

        for dir in ${dirs}; do
          path="kubernetes/$dir/"
          if [[ ! -d "$path" ]]; then
            echo "Expected directory $path not found." >&2
            exit 1
          fi

          shopt -s nullglob
          files=("$path"*.yml "$path"*.yaml)
          shopt -u nullglob
          if [[ ${#files[@]} -eq 0 ]]; then
            echo "No manifest files found in $path." >&2
            exit 1
          fi

          kubectl apply --dry-run="${mode}" -f "$path"
        done

        if [[ "$mode" == "client" ]]; then
          echo "Client dry-run skips server-side validation; set dry-run-mode=server when cluster access is available." >> "$GITHUB_STEP_SUMMARY"
        fi

        echo "${{ inputs.stage }} validation completed using ${mode} dry-run" >> "$GITHUB_STEP_SUMMARY"
